CC := gcc
CFLAGS := -Wall -Werror -Wpedantic -Wextra
CFILES := print.c main.c copy.c
HDRS := print.h errors.h copy.h
OBJS := print.o main.o copy.o

build:
	$(CC) $(CLFAGS) $(CFILES) $(HDRS) -o app.exe
